const INGREDIENTS_LIST = [
	'Jalapeno',
	'Scotch Bonnet',
	'Olive Oil',
	'Yellow Pepper',
	'Duck Fat',
	'Cold Water',
	'Dill',
	'Cumin Seeds',
	'Hazlenuts',
	'Wild Mushrooms',
	'Red Wine Jelly',
	'Smoked Salmon',
	'Salted Butter',
	'Dark Soft Brown Sugar',
	'Coriander Seeds',
	'Beef',
	'Semi-skimmed Milk',
	'Caraway Seed',
	'Brandy',
	'Rice Krispies',
	'White Fish',
	'Tuna',
	'Fajita Seasoning',
	'Cajun',
	'Extra Virgin Olive Oil',
	'Brussels Sprouts',
	'Clams',
	'Massaman Curry Paste',
	'Red Wine',
	'Rapeseed Oil',
	'Doner Meat',
	'Baguette',
	'Rice Vinegar',
	'Bun',
	'Floury Potatoes',
	'Aubergine',
	'Oatmeal',
	'Sherry',
	'Cheese',
	'Polish Sausage',
	'Mars Bar',
	'Blueberries',
	'Green Olives',
	'Pappardelle Pasta',
	'Ham',
	'Celeriac',
	'Chicken Breast',
	'Yellow Food Colouring',
	'Mushrooms',
	'Bramley Apples',
	'Onion',
	'King Prawns',
	'Whole Milk',
	'Mixed Spice',
	'Fermented Black Beans',
	'Pork Chops',
	'Pitted Black Olives',
	'Mirin',
	'Celery Salt',
	'Refried Beans',
	'Tarragon Leaves',
	'Cubed Feta Cheese',
	'Kidney Beans',
	'Cinnamon Stick',
	'Squid',
	'Baking Powder',
	'Smoked Haddock',
	'Spring Onions',
	'Almond Extract',
	'Sake',
	'Madras Paste',
	'Light Rum',
	'Tomatoes',
	'Thai Green Curry Paste',
	'Noodles',
	'Mulukhiyah',
	'Single Cream',
	'Ackee',
	'Harissa Spice',
	'Star Anise',
	'Sauerkraut',
	'Marzipan',
	'Unsalted Butter',
	'Crusty Bread',
	'Glace Cherry',
	'Warm Water',
	'Coconut Cream',
	'Free-range Eggs, Beaten',
	'Baby Squid',
	'Flax Eggs',
	'Lasagne Sheets',
	'Chilled Butter',
	'Charlotte Potatoes',
	'Dried Fruit',
	'Ghee',
	'Apricot Jam',
	'Cannellini Beans',
	'Smoked Paprika',
	'Beef Shin',
	'Mozzarella',
	'Fennel Bulb',
	'Buns',
	'Cardamom',
	'Red Wine Vinegar',
	'Turmeric Powder',
	'White Wine Vinegar',
	'Paccheri Pasta',
	'Chicken Breasts',
	'Lamb Loin Chops',
	'Christmas Pudding',
	'Mustard Seeds',
	'Black Pepper',
	'Macaroni',
	'Salt',
	'Potatoes',
	'Lime',
	'Bouquet Garni',
	'Lamb Shoulder',
	'English Mustard',
	'Fideo',
	'Iceberg Lettuce',
	'Avocado',
	'Orange Zest',
	'Challots',
	'Raw King Prawns',
	'Peanuts',
	'Orange',
	'Shredded Mexican Cheese',
	'Biryani Masala',
	'Oats',
	'Quinoa',
	'Egg Plants',
	'Monkfish',
	'Golden Syrup',
	'Oregano',
	'Goose Fat',
	'Black Pudding',
	'Swede',
	'Basil Leaves',
	'Bread',
	'Parmesan Cheese',
	'Granulated Sugar',
	'Ciabatta',
	'Onion Salt',
	'Doubanjiang',
	'Baby Aubergine',
	'Vegetable Stock Cube',
	'Cheese Curds',
	'White Wine',
	'Chicken Thighs',
	'Vegetable Stock',
	'Rhubarb',
	'Prosciutto',
	'Candied Peel',
	'Parma Ham',
	'Mint',
	'Tomato Ketchup',
	'Rum',
	'Tofu',
	'Raspberries',
	'Buckwheat',
	'Custard Powder',
	'Fresh Basil',
	'Ground Beef',
	'Frozen Peas',
	'Jam',
	'Thai Red Curry Paste',
	'Colby Jack Cheese',
	'Shiitake Mushrooms',
	'Duck Legs',
	'Lemon Zest',
	'Rosemary',
	'Boiling Water',
	'Heavy Cream',
	'Dry White Wine',
	'Beetroot',
	'Peaches',
	'Fries',
	'Raspberry Jam',
	'Green Pepper',
	'English Muffins',
	'Sun-Dried Tomatoes',
	'Green Red Lentils',
	'Pecan Nuts',
	'Butternut Squash',
	'Tomato Puree',
	'Cooking wine',
	'Naan Bread',
	'Chicken Stock Cube',
	'Mustard Powder',
	'Coriander Leaves',
	'Sultanas',
	'Fish Sauce',
	'Garlic Sauce',
	'Free-range Egg, Beaten',
	'Pilchards',
	'Caramel Sauce',
	'Turmeric',
	'Red Chilli Powder',
	'Cream Cheese',
	'Roasted Vegetables',
	'Mussels',
	'Walnuts',
	'Spaghetti',
	'Gelatine Leafs',
	'Persian Cucumber',
	'Garlic Clove',
	'Dark Brown Soft Sugar',
	'Ginger',
	'Salmon',
	'Paella Rice',
	'Dried Apricots',
	'Ricotta',
	'Tomato',
	'Cacao',
	'Chicken',
	'Lettuce',
	'Beef Fillet',
	'Cod',
	'Tomato Sauce',
	'Custard',
	'Plain Flour',
	'Shredded Monterey Jack Cheese',
	'Eggs',
	'Beef Gravy',
	'Butter',
	'Green Beans',
	'Duck Sauce',
	'Lean Minced Beef',
	'Zucchini',
	'Almonds',
	'Sunflower Oil',
	'Butter Beans',
	'Self-raising Flour',
	'Squash',
	'Goats Cheese',
	'Turkey Mince',
	'Wholegrain Bread',
	'Starch',
	'Creamed Corn',
	'Red Chilli',
	'Ginger Paste',
	'Ground Pork',
	'Clotted Cream',
	'Cinnamon',
	'Egg',
	'Soya Milk',
	'Bicarbonate Of Soda',
	'Fettuccine',
	'Bread Rolls',
	'Courgettes',
	'Leek',
	'Miniature Marshmallows',
	'Toffee Popcorn',
	'Currants',
	'Sushi Rice',
	'Chicken Stock Concentrate',
	'Fish Stock',
	'Udon Noodles',
	'Tortillas',
	'Balsamic Vinegar',
	'Ginger Garlic Paste',
	'Black Olives',
	'Broad Beans',
	'Cherry Tomatoes',
	'Bacon',
	'Sesame Seed',
	'Sour Cream',
	'Desiccated Coconut',
	'Freshly Chopped Parsley',
	'Condensed Milk',
	'Curry Powder',
	'Parmesan',
	'Vine Leaves',
	'Plum Tomatoes',
	'Egg Yolks',
	'Jerk',
	'Cashew Nuts',
	'White Fish Fillets',
	'Kosher Salt',
	'Sweet Potatoes',
	'White Flour',
	'Mascarpone',
	'Sugar',
	'Enchilada Sauce',
	'Muffins',
	'Brown Lentils',
	'Caster Sugar',
	'Borlotti Beans',
	'Penne Rigate',
	'Peas',
	'Yellow Onion',
	'Stir-fry Vegetables',
	'Garam Masala',
	'Sausages',
	'Tamarind Ball',
	'Cherry',
	'Truffle Oil',
	'Vanilla Extract',
	'Chives',
	'Light Brown Soft Sugar',
	'Red Pepper',
	'Beef Kidney',
	'Tabasco Sauce',
	'Cabbage',
	'Pears',
	'Ginger Cordial',
	'Minced Beef',
	'Powdered Sugar',
	'Pork',
	'Cayenne Pepper',
	'Paprika',
	'Apples',
	'Strawberries',
	'Gherkin Relish',
	'Bulgur Wheat',
	'Fromage Frais',
	'Pinto Beans',
	'Sesame Seed Burger Buns',
	'Rolled Oats',
	'Fruit Mix',
	'Rose water',
	'Salt Cod',
	'Apricot',
	'Baked Beans',
	'Greek Yogurt',
	'Turnips',
	'Vermicelli Pasta',
	'Treacle',
	'Ancho Chillies',
	'Mackerel',
	'Worcestershire Sauce',
	'Celery',
	'Wonton Skin',
	'Lemons',
	'Broccoli',
	'Bowtie Pasta',
	'Tripe',
	'Tagliatelle',
	'Oysters',
	'Flaked Almonds',
	'Filo Pastry',
	'Haricot Beans',
	'Maple Syrup',
	'Stout',
	'Egg White',
	'Farfalle',
	'Diced Tomatoes',
	'Water Chestnut',
	'Yukon Gold Potatoes',
	'Wood Ear Mushrooms',
	'Duck',
	'Malt Vinegar',
	'Parsley',
	'Saffron',
	'Ground Cumin',
	'Lard',
	'French Lentils',
	'Brie',
	'Nutmeg',
	'Hard Taco Shells',
	'Couscous',
	'Caramel',
	'Tahini',
	'Chestnuts',
	'Cumin',
	'Grand Marnier',
	'Italian Fennel Sausages',
	'Tinned Tomatos',
	'Gruyère',
	'Stilton Cheese',
	'Barbeque Sauce',
	'Haddock',
	'Mozzarella Balls',
	'Thyme',
	'Chocolate Chips',
	'Vegetable Oil',
	'Sriracha',
	'Mixed Grain',
	'Jasmine Rice',
	'Vinaigrette Dressing',
	'Linguine Pasta',
	'Parmigiano-reggiano',
	'Toor Dal',
	'Dill Pickles',
	'Fenugreek',
	'Pine Nuts',
	'Onions',
	'Black Treacle',
	'Banana',
	'Fresh Thyme',
	'Dark Brown Sugar',
	'Red Chile Flakes',
	'Tamarind Paste',
	'Ice Cream',
	'Figs',
	'Coconut Milk',
	'Horseradish',
	'Tiger Prawns',
	'Basil',
	'Cloves',
	'Shallots',
	'Pecorino',
	'Corn Flour',
	'Water',
	'Pita Bread',
	'Raisins',
	'Rice Noodles',
	'Red Pepper Flakes',
	'Lemon',
	'Passata',
	'Cucumber',
	'Chopped Parsley',
	'Yogurt',
	'Oxtail',
	'Dark Soy Sauce',
	'Kale',
	'Little Gem Lettuce',
	'Green Salsa',
	'Peanut Butter',
	'Lamb Leg',
	'Pepper',
	'Bean Sprouts',
	'Minced Pork',
	'Double Cream',
	'Redcurrants',
	'Coco Sugar',
	'Paneer',
	'Whole Wheat',
	'Dried Oregano',
	'Rice Stick Noodles',
	'Cashews',
	'White Vinegar',
	'Canola Oil',
	'Garlic',
	'Apple Cider Vinegar',
	'Potatoe Buns',
	'White Chocolate Chips',
	'Creme Fraiche',
	'Lemon Juice',
	'Carrots',
	'Coriander',
	'Minced Garlic',
	'Blackberries',
	'Mayonnaise',
	'Grape Tomatoes',
	'Italian Seasoning',
	'Hot Beef Stock',
	'Mixed Peel',
	'Ground Almonds',
	'Cider',
	'Asparagus',
	'Thai Fish Sauce',
	'Baby Plum Tomatoes',
	'Puff Pastry',
	'Cheddar Cheese',
	'White Chocolate',
	'Fennel',
	'Capers',
	'Blue Food Colouring',
	'Kielbasa',
	'Goat Meat',
	'Chili Powder',
	'Chicken Stock',
	'Vine Tomatoes',
	'Dark Chocolate',
	'Beef Brisket',
	'Chicken Legs',
	'Marjoram',
	'Lentils',
	'Rice Vermicelli',
	'Black Beans',
	'Feta',
	'Sardines',
	'Lamb Kidney',
	'Cocoa',
	'Sugar Snap Peas',
	'Soy Sauce',
	'Potato Starch',
	'Chilli Powder',
	'Red Snapper',
	'Rigatoni',
	'Beef Stock',
	'Plain Chocolate',
	'Icing Sugar',
	'Dijon Mustard',
	'Muscovado Sugar',
	'Chilli',
	'Almond Milk',
	'Allspice',
	'Anchovy Fillet',
	'Braeburn Apples',
	'Sea Salt',
	'Lamb',
	'Dark Rum',
	'Vinegar',
	'Lamb Mince',
	'Gochujang',
	'Cream',
	'Oil',
	'Milk Chocolate',
	'Monterey Jack Cheese',
	'Mustard',
	'Small Potatoes',
	'Suet',
	'Rice',
	'Chinese Broccoli',
	'Orange Blossom Water',
	'Breadcrumbs',
	'Peanut Oil',
	'Bay Leaves',
	'Flour Tortilla',
	'Brown Sugar',
	'Mincemeat',
	'Pumpkin',
	'Smoky Paprika',
	'Pretzels',
	'Peanut Brittle',
	'Ground Ginger',
	'Peanut Cookies',
	'Basmati Rice',
	'Fennel Seeds',
	'Rocket',
	'Khus Khus',
	'Herring',
	'Egg Rolls',
	'Medjool Dates',
	'Chopped Tomatoes',
	'Brown Rice',
	'Milk',
	'Dark Chocolate Chips',
	'Sichuan Pepper',
	'Red Onions',
	'Full Fat Yogurt',
	'Digestive Biscuits',
	'Demerara Sugar',
	'Vegan Butter',
	'Salsa',
	'Spinach',
	'Canned Tomatoes',
	'Cornstarch',
	'Beef Stock Concentrate',
	'Prawns',
	'Hotsauce',
	'Vanilla',
	'Sesame Seed Oil',
	'Ras el hanout',
	'Yeast',
	'Meringue Nests',
	'Red Food Colouring',
	'Chorizo',
	'Rice wine',
	'Sage',
	'Cheese Slices',
	'Chestnut Mushroom',
	'Jerusalem Artichokes',
	'Pickle Juice',
	'Scallions',
	'Bay Leaf',
	'Gouda Cheese',
	'Honey',
	'Pink Food Colouring',
	'Veal',
	'Green Chilli',
	'Flour',
	'Cilantro',
	'Chopped Onion',
	'Corn Tortillas',
	'Garlic Powder',
	'Shortcrust Pastry',
	'Oyster Sauce',
	'Sweetcorn',
	'Shortening',
	'Chickpeas',
]

module.exports = { INGREDIENTS_LIST }
